version: '3.8'

services:
  # Main API service
  iris-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - DATABASE_URL=sqlite:///./logs.db
      - USE_MLFLOW_REGISTRY=true
      - MLFLOW_MODEL_NAME=iris-classifier
    volumes:
      - ./api:/app/api
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - iris-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MLflow tracking server
  mlflow:
    build: ./mlflow
    ports:
      - "5001:5001"
    volumes:
      # Use a named volume for the database to handle permissions correctly.
      - mlflow_db_data:/db
      # Use a bind mount for artifacts so train.py can access them.
      - ./mlruns:/mlruns
    networks:
      - iris-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - iris-network
    restart: unless-stopped
    profiles:
      - monitoring

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - iris-network
    restart: unless-stopped
    profiles:
      - monitoring
    depends_on:
      - prometheus

volumes:
  # Add the new named volume for the mlflow database
  mlflow_db_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  iris-network:
    driver: bridge
