services:
  # FastAPI ML Service - Free Tier
  - type: web
    name: iris-ml-api
    env: python
    plan: free
    runtime: python-3.11.0
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-render.txt
      mkdir -p artifacts
      python src/train.py
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: ENVIRONMENT
        value: production
    
  # Static Site for Frontend - Free Tier  
  - type: web
    name: iris-ml-frontend
    env: static
    buildCommand: echo "Static site ready"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html