# Environment-specific deployment configurations
# This file defines different deployment environments and their settings

environments:
  development:
    name: "Development"
    description: "Local development environment with hot reload"
    docker:
      image_tag: "dev"
      container_name: "iris-api-dev"
      port: 8000
      restart_policy: "no"
    environment_vars:
      DEBUG: "true"
      LOG_LEVEL: "DEBUG"
      USE_MLFLOW_REGISTRY: "false"
      DATABASE_URL: "sqlite:///./logs.db"
      LOG_PREDICTIONS: "true"
      LOG_REQUESTS: "true"
    volumes:
      - "./api:/app/api"
      - "./src:/app/src"
      - "./logs:/app/logs"
      - "./data:/app/data"
      - "./artifacts:/app/artifacts"
    health_check:
      enabled: true
      interval: "30s"
      timeout: "10s"
      retries: 3
    monitoring:
      prometheus: false
      grafana: false

  staging:
    name: "Staging"
    description: "Pre-production staging environment"
    docker:
      image_tag: "staging"
      container_name: "iris-api-staging"
      port: 8001
      restart_policy: "unless-stopped"
    environment_vars:
      DEBUG: "false"
      LOG_LEVEL: "INFO"
      USE_MLFLOW_REGISTRY: "true"
      DATABASE_URL: "sqlite:///./logs.db"
      LOG_PREDICTIONS: "true"
      LOG_REQUESTS: "true"
      MLFLOW_TRACKING_URI: "http://mlflow-staging:5001"
    volumes:
      - "./logs:/app/logs"
      - "./data:/app/data:ro"
      - "./artifacts:/app/artifacts:ro"
      - "staging_mlflow_data:/app/mlruns"
    health_check:
      enabled: true
      interval: "30s"
      timeout: "10s"
      retries: 5
    monitoring:
      prometheus: true
      grafana: true
    resources:
      memory: "1g"
      cpus: "1.0"

  production:
    name: "Production"
    description: "Production environment with full monitoring"
    docker:
      image_tag: "latest"
      container_name: "iris-api-prod"
      port: 8000
      restart_policy: "unless-stopped"
    environment_vars:
      DEBUG: "false"
      LOG_LEVEL: "INFO"
      USE_MLFLOW_REGISTRY: "true"
      DATABASE_URL: "sqlite:///./logs.db"
      LOG_PREDICTIONS: "true"
      LOG_REQUESTS: "true"
      MLFLOW_TRACKING_URI: "http://mlflow-prod:5001"
      MAX_REQUEST_SIZE: "2048"
      REQUEST_TIMEOUT: "60"
    volumes:
      - "/var/log/iris-api:/app/logs"
      - "/data/iris-api:/app/data:ro"
      - "/models/iris-api:/app/artifacts:ro"
      - "production_mlflow_data:/app/mlruns"
    health_check:
      enabled: true
      interval: "30s"
      timeout: "10s"
      retries: 5
      start_period: "60s"
    monitoring:
      prometheus: true
      grafana: true
      alerts: true
    resources:
      memory: "2g"
      cpus: "2.0"
    security:
      user: "1000:1000"
      read_only: true
      no_new_privileges: true
    backup:
      enabled: true
      schedule: "0 2 * * *"  # Daily at 2 AM
      retention_days: 30

# Global deployment settings
global:
  docker_registry: "docker.io"
  image_name: "iris-classifier-api"
  network_name: "iris-network"
  
  # Default resource limits
  default_resources:
    memory: "512m"
    cpus: "0.5"
  
  # Health check defaults
  default_health_check:
    interval: "30s"
    timeout: "10s"
    retries: 3
    start_period: "30s"
  
  # Monitoring defaults
  monitoring:
    prometheus_port: 9090
    grafana_port: 3000
    metrics_path: "/metrics"
  
  # Backup defaults
  backup:
    retention_days: 7
    compression: true