apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-api-config
  namespace: iris-api
  labels:
    app: iris-classifier
data:
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  USE_MLFLOW_REGISTRY: "false"
  DATABASE_URL: "sqlite:///./logs.db"
  LOG_PREDICTIONS: "true"
  LOG_REQUESTS: "true"
  MAX_REQUEST_SIZE: "2048"
  REQUEST_TIMEOUT: "60"
  CORS_ORIGINS: '["*"]'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-api-prometheus-config
  namespace: iris-api
  labels:
    app: iris-classifier
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    scrape_configs:
      - job_name: 'iris-api'
        static_configs:
          - targets: ['iris-api-service:8000']
        metrics_path: '/metrics'
        scrape_interval: 30s

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

  alert_rules.yml: |
    groups:
    - name: iris-api-alerts
      rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      - alert: ModelPredictionFailure
        expr: rate(ml_prediction_errors_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Model prediction failures detected"
          description: "Prediction error rate is {{ $value }} errors per second"