apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-api-logs-pvc
  namespace: iris-api
  labels:
    app: iris-classifier
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-api-data-pvc
  namespace: iris-api
  labels:
    app: iris-classifier
    component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-api-artifacts-pvc
  namespace: iris-api
  labels:
    app: iris-classifier
    component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard